/** @format */
export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const ADMIN_CREATE_REQUEST = "ADMIN_CREATE_REQUEST";
export const ADMIN_CREATE_SUCCESS = "ADMIN_CREATE_SUCCESS";
export const ADMIN_CREATE_FAIL = "ADMIN_CREATE_FAIL";