/** @format */
export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const ADMIN_CREATE_REQUEST = "ADMIN_CREATE_REQUEST";
export const ADMIN_CREATE_SUCCESS = "ADMIN_CREATE_SUCCESS";
export const ADMIN_CREATE_FAIL = "ADMIN_CREATE_FAIL";

export const ADMINS_LIST_REQUEST = "ADMINS_LIST_REQUEST";
export const ADMINS_LIST_SUCCESS = "ADMINS_LIST_SUCCESS";
export const ADMINS_LIST_FAIL = "ADMINS_LIST_FAIL";

export const ADMIN_DISABLE = "ADMIN_DISABLE"
export const ADMIN_ENABLE = "ADMIN_ENABLE"
export const ADMIN_DELETE = "ADMIN_DELETE"

export const ADMIN_UPDATE_REQUEST = "ADMIN_UPDATE_REQUEST";
export const ADMIN_UPDATE_SUCCESS = "ADMIN_UPDATE_SUCCESS";
export const ADMIN_UPDATE_FAIL = "ADMIN_UPDATE_FAIL";
