/** @format */
export const DEVELOPERS_LIST_REQUEST = "DEVELOPERS_LIST_REQUEST";
export const DEVELOPERS_LIST_SUCCESS = "DEVELOPERS_LIST_SUCCESS";
export const DEVELOPERS_LIST_FAIL = "DEVELOPERS_LIST_FAIL";

export const DEVELOPER_DETAILS_REQUEST = "DEVELOPER_DETAILS_REQUEST";
export const DEVELOPER_DETAILS_SUCCESS = "DEVELOPER_DETAILS_SUCCESS";
export const DEVELOPER_DETAILS_FAIL = "DEVELOPER_DETAILS_FAIL";

export const DEVELOPER_CREATE_REQUEST = "DEVELOPER_CREATE_REQUEST";
export const DEVELOPER_CREATE_SUCCESS = "DEVELOPER_CREATE_SUCCESS";
export const DEVELOPER_CREATE_FAIL = "DEVELOPER_CREATE_FAIL";

export const DEVELOPER_UPDATE_REQUEST = "DEVELOPER_UPDATE_REQUEST";
export const DEVELOPER_UPDATE_SUCCESS = "DEVELOPER_UPDATE_SUCCESS";
export const DEVELOPER_UPDATE_FAIL = "DEVELOPER_UPDATE_FAIL";
export const DEVELOPER_UPDATE_RESET = "DEVELOPER_UPDATE_RESET";

export const DEVELOPER_DELETE = "DEVELOPER_DELETE";
