/** @format */
export const ENTREPRENEURS_LIST_REQUEST = "ENTREPRENEURS_LIST_REQUEST";
export const ENTREPRENEURS_LIST_SUCCESS = "ENTREPRENEURS_LIST_SUCCESS";
export const ENTREPRENEURS_LIST_FAIL = "ENTREPRENEURS_LIST_FAIL";

export const ENTREPRENEUR_DETAILS_REQUEST = "ENTREPRENEUR_DETAILS_REQUEST";
export const ENTREPRENEUR_DETAILS_SUCCESS = "ENTREPRENEUR_DETAILS_SUCCESS";
export const ENTREPRENEUR_DETAILS_FAIL = "ENTREPRENEUR_DETAILS_FAIL";
