/** @format */
export const ENTREPRENEURS_LIST_REQUEST = "ENTREPRENEURS_LIST_REQUEST";
export const ENTREPRENEURS_LIST_SUCCESS = "ENTREPRENEURS_LIST_SUCCESS";
export const ENTREPRENEURS_LIST_FAIL = "ENTREPRENEURS_LIST_FAIL";

export const ENTREPRENEUR_DETAILS_REQUEST = "ENTREPRENEUR_DETAILS_REQUEST";
export const ENTREPRENEUR_DETAILS_SUCCESS = "ENTREPRENEUR_DETAILS_SUCCESS";
export const ENTREPRENEUR_DETAILS_FAIL = "ENTREPRENEUR_DETAILS_FAIL";

export const ENTREPRENEUR_CREATE_REQUEST = "ENTREPRENEUR_CREATE_REQUEST";
export const ENTREPRENEUR_CREATE_SUCCESS = "ENTREPRENEUR_CREATE_SUCCESS";
export const ENTREPRENEUR_CREATE_FAIL = "ENTREPRENEUR_CREATE_FAIL";

export const ENTREPRENEUR_UPDATE_REQUEST = "ENTREPRENEUR_UPDATE_REQUEST";
export const ENTREPRENEUR_UPDATE_SUCCESS = "ENTREPRENEUR_UPDATE_SUCCESS";
export const ENTREPRENEUR_UPDATE_FAIL = "ENTREPRENEUR_UPDATE_FAIL";
export const ENTREPRENEUR_UPDATE_RESET = "ENTREPRENEUR_UPDATE_RESET";
