export const ENTREPRENEURS_LIST_REQUEST = 'ENTREPRENEURS_LIST_REQUEST';
export const ENTREPRENEURS_LIST_SUCCESS = 'ENTREPRENEURS_LIST_SUCCESS';
export const ENTREPRENEURS_LIST_FAIL = 'ENTREPRENEURS_LIST_FAIL';
